version: '2'
services:
  135026-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "17000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  135026-eureka:
    image: 135026_dockerhub_user/task6-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=135026-eureka"
      - "traefik.frontend.rule=PathPrefixStrip:/135026-eureka"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  135026-zuul:
    image: 135026_dockerhub_user/task6-zuul
    labels:
      - "traefik.port=8080"
      - "traefik.backend=135026-zuul"
      - "traefik.frontend.rule=PathPrefixStrip:/135026-zuul"

  135026-gateway:
    image: 135026_dockerhub_user/task6-gateway
    labels:
      - "traefik.port=8080"
      - "traefik.backend=135026-gateway"
      - "traefik.frontend.rule=PathPrefixStrip:/135026-gateway"

  135026-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: demo
    volumes:
      - 135026-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

#   135026-login:
#     image: 135026_dockerhub_user/task7-login
#     labels:
#       - "traefik.port=8080"
#       - "traefik.backend=135026-login"
#       - "traefik.frontend.rule=PathPrefixStrip:/135026-login"
#     links:
#       - 135026-mysql
#       - 135026-eureka
#  #     - my-zuul
#  #     - my-gateway
#     depends_on:
#       - 135026-mysql
#       - 135026-traefik
#       - 135026-eureka
# #      - my-zuul
# #      - my-gateway

  my-app1:
    image: 135026_dockerhub_user/task6-users
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-app1"
      - "traefik.frontend.rule=PathPrefixStrip:/my-app1"
    links:
      - 135026-mysql
      - 135026-eureka
      - 135026-zuul
      - 135026-gateway
    depends_on:
      - 135026-mysql
      - 135026-traefik
      - 135026-eureka
      - 135026-zuul
      - 135026-gateway

  my-app2:
    image: 135026_dockerhub_user/task6-theaters
    labels:
      - "traefik.port=8080"
      - "traefik.backend=my-app2"
      - "traefik.frontend.rule=PathPrefixStrip:/my-app2"
    links:
      - 135026-mysql
      - 135026-eureka
      - 135026-zuul
      - 135026-gateway
    depends_on:
      - 135026-mysql
      - 135026-traefik
      - 135026-eureka
      - 135026-zuul
      - 135026-gateway

volumes:
  135026-datavolume: {}
