---
spring:
  profiles: default

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL

---
spring:
  profiles: test

spring.jpa:
  hibernate:
    ddl-auto: create-drop

---
spring:
  profiles: local

eureka:
  client:
    service-url:
     defaultZone: http://135026-eureka:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    users: /users/**
    theaters: /theaters/**
    rating: /rating/**
    my-gateway: /135026-gateway/**
    my-login: 
      path: /135026-login/**
      sensitive-headers:

management:
  security:
    enabled: false